sonar.projectKey=aeskrynchenko78_frontend-project-46
sonar.organization=aeskrynchenko78

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=src
sonar.tests=__tests__
sonar.exclusions=node_modules/**,coverage/**,__fixtures__/**
